version: '3'

services:
  static-marks:
    build:
        context: https://github.com/gaerfield/static-marks-docker.git
    image: static-marks
    volumes:
        - ./bookmarks:/bookmarks:ro
        - ./docs:/docs:rw
        - ./template.html:/template.html:ro

